#!/usr/bin/env bash
# This script installs Nginx and configures it to meet the specified requirements.

# Install Nginx with the -y flag for automatic confirmation
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
