#!/usr/bin/env bash
# This script configures Nginx to have a custom 404 page.
sudo apt-get -y update
sudo apt-get -y install nginx

sudo touch /etc/nginx/sites-available/404-page.conf
sudo chmod 666 /etc/nginx/sites-available/404-page.conf

SERVER_CONFIG=$(cat <<EOL
server {
  listen 80;
  server_name 100.25.150.188;

  error_page 404 /404.html;
  location = /404.html {
    internal;
    return 404 "Ceci n'est pas une page\n";
  }
}
EOL
)

printf '%s\n' "$SERVER_CONFIG" | sudo tee /etc/nginx/sites-available/404-page.conf > /dev/null

sudo ln -s /etc/nginx/sites-available/404-page.conf /etc/nginx/sites-enabled/

sudo nginx -t
sudo service nginx restart
