#!/usr/bin/env bash
#This script configures Nginx and add a custom HTTP response header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
sudo chmod 666 /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
sudo touch /var/www/html/404.html
sudo chmod 666 /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo chmod 666 /etc/nginx/sites-available/default
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=16y1AkoZkmQ;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
