#!/usr/bin/env bash
# This script installs and configures HAProxy on lb-01
sudo apt-get -y update
sudo apt-get -y install haproxy

sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo chmod 666 /etc/haproxy/haproxy.cfg
echo "\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend backend-servers

backend backend-servers
    balance roundrobin
    server 324885-web-01 100.25.150.188:80 check
    server 324885-web-02 34.229.186.16:80 check
" >> /etc/haproxy/haproxy.cfg

sudo sed -i 's/^ENABLED=.*/ENABLED=1/' /etc/default/haproxy

sudo service haproxy restart
