#!/usr/bin/env bash
# Function to handle SIGINT signal
function handle_sigint {
    echo "Y U no love me?!"
}

# Function to handle SIGTERM and SIGQUIT signals
function handle_sigterm {
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit
}

# Register signal handlers
trap handle_sigint SIGINT
trap handle_sigterm SIGTERM SIGQUIT

# Create the PID file
echo $$ > /var/run/myscript.pid

# Display "To infinity and beyond" indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 1
done
