#!/usr/bin/env bash

# Function to handle SIGTERM signal
function handle_sigterm() {
    echo "I am invincible!!!"
    exit 0
}

# Trap the SIGTERM signal and call the handle_sigterm function
trap handle_sigterm SIGTERM

# Infinite loop to display the message "To infinity and beyond" with a 2-second sleep between iterations
while true; do
    echo "To infinity and beyond"
    sleep 2
done
