#!/usr/bin/env bash
# Function to handle SIGTERM signal
function handle_sigterm() {
    echo "I am invincible!!!"
    exit 0
}

trap handle_sigterm SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
