#!/usr/bin/env bash

# This script is displaying "Best School" 10 times

# Initialize the counter
count=1

# Using a while loop to display "Best School" 10 times
while [ $count -le 10 ]
do
    echo "Best School"
    # Increment the counter
    ((count++))
done
