#!/usr/bin/env bash

# This script is displaying "Best School" 10 times

# Initialize the counter
count=0

# Using an until loop to display "Best School" 10 times
until [ $count -ge 10 ]
do
    echo "Best School"
    # Increment the counter
    ((count++))
done
