#!/bin/bash
# This script configures Nginx to run as the nginx user and listen on port 8080
sudo service nginx stop
sudo chown -R nginx:nginx /etc/nginx /var/log/nginx /var/lib/nginx /var/cache/nginx
sudo sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/nginx.conf
sudo service nginx start
