#!/usr/bin/env bash

# Identify the process ID of the Gunicorn master
MASTER_PID=$(pgrep gunicorn)

# Initiate a HUP signal to the Gunicorn master process, triggering a graceful worker reload
kill -HUP "$MASTER_PID"
